language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_4dafad2c851f_key -iv $encrypted_4dafad2c851f_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa

- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ./ssh_config ~/.ssh/config
after_script:
- scp -o stricthostkeychecking=no index.js root@59.110.168.70:/
