language: node_js
node_js:
- '6'
script: karma start karma.conf.js — single-run
before_install:
- openssl aes-256-cbc -K $encrypted_4dafad2c851f_key -iv $encrypted_4dafad2c851f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 59.110.168.70\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
after_success:
- ssh root@59.110.168.70 'mkdir sucess'
